In [ ]:
Problem 1: Add 2 randomly generated Numpy matrices

In [ ]:
Sub task: create a random no matrix of size 5X4

In [1]:
import numpy as np
import math

In [2]:
A = np.random.randint(1,10, (5,4))
B = np.random.randint(1,10, (5,4))
C = np.zeros((5,4))
print(A)
# print(A.shape)
# print(type(A))
print(B)

[[2 2 1 8]
 [6 5 5 7]
 [9 9 5 6]
 [8 4 7 6]
 [8 5 6 8]]
[[4 7 6 4]
 [3 6 3 6]
 [6 2 8 7]
 [9 2 8 7]
 [1 2 3 5]]


In [42]:
# Logic: Ci,j = Ai,j + Bi,j

rows, cols = A.shape

print(rows, cols)
for i in range(rows):
    for j in range(cols):
        C[i,j] = A[i,j] + B[i,j]

print(C)

5 4
[[10. 15.  7. 17.]
 [11. 10.  5.  9.]
 [ 9. 10.  7.  8.]
 [12. 15. 13. 15.]
 [ 7. 10. 10. 10.]]


In [43]:
C = A + B
print(C)

[[10 15  7 17]
 [11 10  5  9]
 [ 9 10  7  8]
 [12 15 13 15]
 [ 7 10 10 10]]


In [ ]:
Time Complexity = O(nm) where n is no. of rows, m is no. of columns
= O(n^2) if m= n

Space Complexity = O(1)
we don't count the input and output variables for space complexity, we just count i,j, rows, cols which hold constant values

In [ ]:
Exercise: Add two randomly generated NumPy 3D-matrices(tensor) using loops

In [68]:
A = np.random.randint(1,10, (5,4,3))
B = np.random.randint(1,10, (5,4,3))
C = np.zeros((5,4,3))
# print(A)
print(A.shape)
# print(type(A))
# print(B)

(5, 4, 3)


In [72]:
rows, cols, dimension = A.shape

print(rows, cols, dimension)
for i in range(rows):
    for j in range(cols):
        for k in range(dimension):
            C[i,j,k] = A[i,j,k] + B[i,j,k]

print(C)

5 4 3
[[[10.  9. 12.]
  [14. 14. 10.]
  [10. 17.  2.]
  [ 9. 13. 12.]]

 [[ 7. 16.  8.]
  [17.  9. 11.]
  [11.  4.  8.]
  [ 8.  9.  6.]]

 [[14.  8.  3.]
  [10. 10.  9.]
  [11. 16.  7.]
  [ 9.  7. 15.]]

 [[17. 12. 15.]
  [10. 13.  5.]
  [ 4.  7.  6.]
  [16.  2. 15.]]

 [[ 7. 13. 10.]
  [11. 17. 12.]
  [ 8.  7. 12.]
  [ 7.  7. 12.]]]


In [ ]:
Problem 2: Find if a given 2D-point is inside (or) outside a circle

In [ ]:
In a 2d space circle can be represented using radius (Cx, Cy) and its radius
Point can be represented by 2 points say Px, Py

to check if a point is inside/outside the circle, compute the distance (d) of the point from the centre of the circle, with the radius(r)
if d < r: inside the circle
if d==r: on the circle
if d > r: outside the circle

d = sqrt((Cx - Px)^2 + (Cy - Py)^2)

In [45]:
(cx, cy, r) = input("Enter Cx, Cy, R").split()
(px, py) = input("Enter Px, Py").split()

In [46]:
print(cx, cy, r)
print(px, py)

0 0 5
1 1


In [47]:
cx = float(cx)
cy = float(cy)
r = float(r)
px = float(px)
py = float(py)

d = math.sqrt((cx - px)**2 + (py-px)**2)
print(d)

if d > r:
    print("Point is outside the circle")
elif d == r:
    print("Point is on the circle")
else:
    print("Point is outside the circle")

1.0
Point is outside the circle


In [ ]:
Exercise: Find if a given 2D-point is inside (or) outside a rectangle 

In [ ]:
Take the diagonal co-ordinates of the rectangle and see if the top y co-ordinate is greater than the point's y-cordinate and the top x co-ordinate is lesser than the point's x-cordinate
And
the bottom y co-ordinate is greater than the point's y-cordinate and the bottom x co-ordinate is greater than the point's x-cordinate

In [80]:
(x1, y1) = input("Enter top left co-ordinates").split()
(x2, y2) = input("Enter bottom right co-ordinates").split()
(px, py) = input("Enter Px, Py").split()

print(x1, y1, x2, y2, px, py)

0 5 5 0 2 2


In [81]:
x1 = float(x1)
y1 = float(y1)
x2 = float(x2)
y2 = float(y2)
px = float(px)
py = float(py)

if px >= x1 and py <= y1 and px <= x2 and py >= y2:
    print("point is inside the circle")
else:
    print("point is outside the circle")

point is inside the circle


In [ ]:
Problem 3: NumPy ndarray manipulation operations

In [49]:
#reshape errors

In [50]:
A = np.random.rand(5,4)
print(A)

[[0.15123651 0.6211914  0.31601582 0.21137513]
 [0.53648543 0.90728292 0.68856478 0.89592441]
 [0.28893051 0.28623808 0.25528695 0.79920401]
 [0.39107899 0.48115232 0.89492875 0.20947957]
 [0.9779929  0.761051   0.76162072 0.90882229]]


In [52]:
#convert matrix to vector
np.reshape(A, 20, 'C') #array, shape int/tuple, major order
#C: row major order: o/p is arranged by rows
#F: column major order: o/p is arranged by columns

array([0.15123651, 0.6211914 , 0.31601582, 0.21137513, 0.53648543,
       0.90728292, 0.68856478, 0.89592441, 0.28893051, 0.28623808,
       0.25528695, 0.79920401, 0.39107899, 0.48115232, 0.89492875,
       0.20947957, 0.9779929 , 0.761051  , 0.76162072, 0.90882229])

In [53]:
np.reshape(A, 20, 'F')

array([0.15123651, 0.53648543, 0.28893051, 0.39107899, 0.9779929 ,
       0.6211914 , 0.90728292, 0.28623808, 0.48115232, 0.761051  ,
       0.31601582, 0.68856478, 0.25528695, 0.89492875, 0.76162072,
       0.21137513, 0.89592441, 0.79920401, 0.20947957, 0.90882229])

In [54]:
#convert 5X4 to 4X5
np.reshape(A, (4,5), 'C')

array([[0.15123651, 0.6211914 , 0.31601582, 0.21137513, 0.53648543],
       [0.90728292, 0.68856478, 0.89592441, 0.28893051, 0.28623808],
       [0.25528695, 0.79920401, 0.39107899, 0.48115232, 0.89492875],
       [0.20947957, 0.9779929 , 0.761051  , 0.76162072, 0.90882229]])

In [55]:
#convert 5X4 to 4X5
np.reshape(A, (4,-1), 'C')
#-1 means o/p should have 4 rows and rest of the elements should be arranged in columns - it will automatically interpret 4,5 

array([[0.15123651, 0.6211914 , 0.31601582, 0.21137513, 0.53648543],
       [0.90728292, 0.68856478, 0.89592441, 0.28893051, 0.28623808],
       [0.25528695, 0.79920401, 0.39107899, 0.48115232, 0.89492875],
       [0.20947957, 0.9779929 , 0.761051  , 0.76162072, 0.90882229]])

In [56]:
#convert 5X4 to 4X5
np.reshape(A, (-1,5), 'C')
#-1 means o/p should have 5 columns and rest of the elements should be arranged in rows - it will automatically interpret 4,5 

array([[0.15123651, 0.6211914 , 0.31601582, 0.21137513, 0.53648543],
       [0.90728292, 0.68856478, 0.89592441, 0.28893051, 0.28623808],
       [0.25528695, 0.79920401, 0.39107899, 0.48115232, 0.89492875],
       [0.20947957, 0.9779929 , 0.761051  , 0.76162072, 0.90882229]])

In [ ]:
Exercise: take a tensor of size 4X5X6 and convert it into a tensor of vector and then matrix (10X12).

In [83]:
A = np.random.rand(4,5,6)
# print(A)

In [85]:
#convert matrix to vector
# np.reshape(A, 120, 'C') 

In [87]:
# np.reshape(A, (10,12), 'C')

In [57]:
#Stacking

In [58]:
A = np.random.rand(5,4);
print(A);

B= np.random.rand(5,2);
print(B)

[[0.74869913 0.35120044 0.31996793 0.04173871]
 [0.47029847 0.6158651  0.97657453 0.78661982]
 [0.11710376 0.80480159 0.27420699 0.93882788]
 [0.23452822 0.09899583 0.58021079 0.5005807 ]
 [0.34756637 0.87553446 0.77096327 0.89561755]]
[[0.68724449 0.7204441 ]
 [0.33742178 0.83333191]
 [0.2951784  0.1662942 ]
 [0.56926271 0.81297694]
 [0.42955497 0.08360913]]


In [59]:
#we can combine/concatenate/stack matrices horizontally or vertically
# horizontal stacking ie add the 2 cols of B in A, cant stack them vertically

In [60]:
#horizontal stacking
C = np.hstack((A, B)); # input: takes a tuple of nd arrays
print(C)

[[0.74869913 0.35120044 0.31996793 0.04173871 0.68724449 0.7204441 ]
 [0.47029847 0.6158651  0.97657453 0.78661982 0.33742178 0.83333191]
 [0.11710376 0.80480159 0.27420699 0.93882788 0.2951784  0.1662942 ]
 [0.23452822 0.09899583 0.58021079 0.5005807  0.56926271 0.81297694]
 [0.34756637 0.87553446 0.77096327 0.89561755 0.42955497 0.08360913]]


In [61]:
A = np.random.rand(5,4);
print(A);

B= np.random.rand(4,4);
print(B)

C = np.hstack((A, B)); #not possible
print(C)

[[0.35941418 0.55837643 0.22651938 0.12433046]
 [0.22795984 0.82724949 0.48311016 0.56970991]
 [0.56006978 0.48054065 0.21426909 0.88199496]
 [0.06814746 0.57181577 0.56385919 0.55497164]
 [0.67176358 0.35301679 0.95824233 0.95136272]]
[[0.56760993 0.78782454 0.6576128  0.74465865]
 [0.56405798 0.06100695 0.73835871 0.80272284]
 [0.09403384 0.40506433 0.76228407 0.36225365]
 [0.19280529 0.96993864 0.1405254  0.3634324 ]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 4

In [62]:
C = np.vstack((A, B))
print(C)

[[0.35941418 0.55837643 0.22651938 0.12433046]
 [0.22795984 0.82724949 0.48311016 0.56970991]
 [0.56006978 0.48054065 0.21426909 0.88199496]
 [0.06814746 0.57181577 0.56385919 0.55497164]
 [0.67176358 0.35301679 0.95824233 0.95136272]
 [0.56760993 0.78782454 0.6576128  0.74465865]
 [0.56405798 0.06100695 0.73835871 0.80272284]
 [0.09403384 0.40506433 0.76228407 0.36225365]
 [0.19280529 0.96993864 0.1405254  0.3634324 ]]


In [63]:
# 3D tensors
A = np.random.rand(5,4,3); # (height, width, colors(R,G,B)/depth) in images is a good way to think of this, refer image 1
print(A.shape);

B= np.random.rand(5,3,3);
print(B.shape)

C = np.hstack((A, B)); #we can combine them horizontally bcoz its height and depth are the same, refer image 2
print(C.shape)

(5, 4, 3)
(5, 3, 3)
(5, 7, 3)


In [88]:
# 3D tensors
A = np.random.rand(5,4,3);
print(A.shape);

B= np.random.rand(4,3,3);
print(B.shape)

C = np.vstack((A,B))
print(C.shape)

C = np.hstack((A, B)); #not possible bcoz height/rows is not the same, refer image 3
print(C.shape)

(5, 4, 3)
(4, 3, 3)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

In [89]:
# 3D tensors
A = np.random.rand(5,4,3);
print(A.shape)

B= np.random.rand(5,4,2); #depth is not matching, , refer image 4
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(5, 4, 2)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 3 and the array at index 1 has size 2

In [66]:
# 3D tensors vstack
A = np.random.rand(5,4,3); # (height, width, colors) in images
print(A.shape);

B= np.random.rand(2,4,3);
print(B.shape)

C = np.vstack((A, B)); #depth and width are matching, therefore vstack is possible, refer image 5
print(C.shape)

(5, 4, 3)
(2, 4, 3)
(7, 4, 3)


In [ ]:
Exercise: Achieve the above transforms using numpy.concatenate https://numpy.org/doc/1.18/reference/generated/numpy.concatenate.html#numpy.concatenate

In [90]:
A = np.random.rand(5,4,3); # (height, width, colors(R,G,B)/depth) in images is a good way to think of this, refer image 1
print(A.shape);

B= np.random.rand(5,3,3);
print(B.shape)

#convert to vector
C = np.concatenate((A,B), axis=None)
print(C)

(5, 4, 3)
(5, 3, 3)
[0.03086933 0.75947417 0.45396616 0.9701289  0.76813515 0.40052889
 0.34182815 0.51209161 0.16440545 0.85158716 0.90109619 0.55349604
 0.65097347 0.84305469 0.6030511  0.31936889 0.966265   0.57772628
 0.46330908 0.89725234 0.47749477 0.99753043 0.37885967 0.93053309
 0.86471898 0.68991913 0.69496302 0.47880651 0.14524946 0.83662523
 0.24462393 0.04311565 0.05262974 0.84950915 0.46014453 0.53065219
 0.381649   0.98693958 0.50597972 0.16246539 0.44355138 0.8973543
 0.66562026 0.34018619 0.16875206 0.51195248 0.91305786 0.26906043
 0.4893187  0.43376475 0.31498331 0.73648794 0.08602304 0.33188912
 0.22025667 0.21600298 0.40543897 0.3847881  0.23580092 0.68597267
 0.70266619 0.43522303 0.87866753 0.33251454 0.2700607  0.02341117
 0.78555061 0.57563542 0.56700124 0.74317694 0.44847849 0.67677867
 0.08753522 0.03843501 0.42849965 0.05780251 0.343295   0.26292377
 0.14762364 0.79759191 0.25711759 0.60143067 0.98649625 0.99810827
 0.25557118 0.58635433 0.83295376 0.6643648

In [91]:
#stack horizontally
C = np.concatenate((A,B), axis=1)
print(C)

[[[0.03086933 0.75947417 0.45396616]
  [0.9701289  0.76813515 0.40052889]
  [0.34182815 0.51209161 0.16440545]
  [0.85158716 0.90109619 0.55349604]
  [0.70266619 0.43522303 0.87866753]
  [0.33251454 0.2700607  0.02341117]
  [0.78555061 0.57563542 0.56700124]]

 [[0.65097347 0.84305469 0.6030511 ]
  [0.31936889 0.966265   0.57772628]
  [0.46330908 0.89725234 0.47749477]
  [0.99753043 0.37885967 0.93053309]
  [0.74317694 0.44847849 0.67677867]
  [0.08753522 0.03843501 0.42849965]
  [0.05780251 0.343295   0.26292377]]

 [[0.86471898 0.68991913 0.69496302]
  [0.47880651 0.14524946 0.83662523]
  [0.24462393 0.04311565 0.05262974]
  [0.84950915 0.46014453 0.53065219]
  [0.14762364 0.79759191 0.25711759]
  [0.60143067 0.98649625 0.99810827]
  [0.25557118 0.58635433 0.83295376]]

 [[0.381649   0.98693958 0.50597972]
  [0.16246539 0.44355138 0.8973543 ]
  [0.66562026 0.34018619 0.16875206]
  [0.51195248 0.91305786 0.26906043]
  [0.66436487 0.34307988 0.53196544]
  [0.55007252 0.48098693 0.37497

In [94]:
# vertical stack
A = np.random.rand(5,4,3);
print(A.shape);

B= np.random.rand(4,4,3);
print(B.shape)

C = np.concatenate((A,B), axis=0)
print(C)

(5, 4, 3)
(4, 4, 3)
[[[0.71459451 0.87754415 0.97338889]
  [0.08842775 0.07895072 0.38238847]
  [0.84714046 0.7185903  0.18293726]
  [0.33404923 0.05241012 0.89227501]]

 [[0.08625666 0.90755657 0.20727117]
  [0.05527943 0.25372786 0.33801459]
  [0.21306502 0.47450876 0.61521604]
  [0.50268833 0.95479588 0.83580836]]

 [[0.45584634 0.06306744 0.32068911]
  [0.75943075 0.28534396 0.97724454]
  [0.06460351 0.35027087 0.94684453]
  [0.64669482 0.32782436 0.61890216]]

 [[0.59972609 0.82807625 0.17426325]
  [0.80827721 0.01358409 0.64266184]
  [0.30139185 0.99623024 0.43187709]
  [0.48603034 0.18108785 0.96861555]]

 [[0.98802602 0.87232364 0.34034161]
  [0.18313565 0.89592765 0.71666736]
  [0.97448087 0.82407621 0.16907821]
  [0.91122973 0.32347272 0.73562416]]

 [[0.65499566 0.63296397 0.16475784]
  [0.43786071 0.99022164 0.56484196]
  [0.65579696 0.07632098 0.34159608]
  [0.38588065 0.63980393 0.5580249 ]]

 [[0.05182843 0.89531812 0.72789387]
  [0.09489683 0.67614867 0.81407025]
  [0.5